name: Deploy To GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy To gh-pages
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
